language: php

os: linux

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

addons:
  postgresql: "9.5"

php:
 - 7.2
 - 7.3

env:
 global:
  - IGNORE_PATHS=amd/build
 matrix:
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=master
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci add-plugin --branch master learnweb/his_unification
  - moodle-plugin-ci install

jobs:
  include:
    # Prechecks against latest Moodle stable only.
    - stage: static
      php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
      script:
      - moodle-plugin-ci phplint
      - moodle-plugin-ci phpcpd
      - moodle-plugin-ci phpmd
      - moodle-plugin-ci codechecker
      - moodle-plugin-ci savepoints
      - moodle-plugin-ci mustache
      - moodle-plugin-ci grunt
      - moodle-plugin-ci validate

    # Smaller build matrix for development builds
    - stage: develop
      php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
      script:
      - moodle-plugin-ci phpunit --coverage-clover
      - cd moodle
      - php -S localhost:8000 >/dev/null 2>&1 &
      - cd ..
      - sleep 10 # Wait for behat to start
      - php moodle/admin/tool/behat/cli/run.php --tags="@block_evasys_sync"

# Default 'test' stage: Unit tests and behat tests against full matrix.
script:
  - moodle-plugin-ci phpunit --coverage-clover
  - cd moodle
  - php -S localhost:8000 >/dev/null 2>&1 &
  - cd ..
  - sleep 10 # Wait for behat to start
  - php moodle/admin/tool/behat/cli/run.php --tags="@block_evasys_sync_fulltest"

after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - static
  - name: develop
    if: branch != master AND (type != pull_request OR head_branch != master) AND (tag IS blank)
  - name: test
    if: branch = master OR (type = pull_request AND head_branch = master) OR (tag IS present)
